
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    root: debug
    org.hibernate.SQL: debug

livereload:
  enabled: true

server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true